# Generated by Django 4.2.2 on 2023-06-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MelodyShare', '0002_privatemusicrecord_protectedmusicrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemusicrecord',
            name='media_file',
            field=models.FileField(null=True, upload_to='private_music/'),
        ),
        migrations.AddField(
            model_name='protectedmusicrecord',
            name='media_file',
            field=models.FileField(null=True, upload_to='protected_music/'),
        ),
        migrations.AddField(
            model_name='publicmusicrecord',
            name='media_file',
            field=models.FileField(null=True, upload_to='public_music/'),
        ),
    ]
