# Generated by Django 4.2.2 on 2023-06-16 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MelodyShare', '0003_privatemusicrecord_media_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemusicrecord',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatemusicrecord',
            name='description',
            field=models.TextField(),
        ),
    ]
