# Generated by Django 4.2.2 on 2023-06-16 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MelodyShare', '0004_privatemusicrecord_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemusicrecord',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='privatemusicrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MelodyShare.newuser'),
        ),
    ]
