# Generated by Django 4.2.2 on 2023-06-18 08:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MelodyShare', '0006_alter_privatemusicrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedmusicrecord',
            name='email_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
